Repository Deepomatic/deepocli, pull requests merged in 2019-10, with the labels that each got.

#105 Fix blur gaussian method
  deepomatic/cli/cmds/infer.py
Labels: READY, bug-fix

#100 Group option by semantic
  deepomatic/cli/cli_parser.py
Labels: READY, feature

#114 More resilient to inference errors
  deepomatic/cli/cmds/feedback.py
  deepomatic/cli/cmds/infer.py
  deepomatic/cli/cmds/studio_helpers/file.py
  deepomatic/cli/cmds/studio_helpers/task.py
  deepomatic/cli/exceptions.py
  deepomatic/cli/frame.py
  deepomatic/cli/input_data.py
  deepomatic/cli/output_data.py
  deepomatic/cli/thread_base.py
  deepomatic/cli/workflow/cloud_workflow.py
  deepomatic/cli/workflow/json_workflow.py
  deepomatic/cli/workflow/rpc_workflow.py
  deepomatic/cli/workflow/workflow_abstraction.py
  requirements.txt
Labels: READY, enhancement

#127 Moved summary after pbar close
  deepomatic/cli/thread_base.py
Labels: READY, bug-fix

#133 Remove useless dependencies
  deepomatic/cli/output_data.py
  requirements.txt
Labels: dependencies

#134 Refactor imports deepomatic-rpc
  deepomatic/cli/output_data.py
  deepomatic/cli/workflow/__init__.py
  deepomatic/cli/workflow/rpc_workflow.py
Labels: READY, feature
