Repository Deepomatic/deepocli, pull requests merged in 2019-12, with the labels that each got.

#144 Fixed wrong exception name in super
  deepomatic/cli/exceptions.py
Labels: bug-fix

#143 Let deepomatic-api check credentials
  deepomatic/cli/workflow/cloud_workflow.py
Labels: feature

#145 Add flake8 checks and fix errors
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  deepomatic/cli/__init__.py
  deepomatic/cli/__main__.py
  deepomatic/cli/cli_parser.py
  deepomatic/cli/common.py
  deepomatic/cli/input_data.py
  deepomatic/cli/json_schema.py
  deepomatic/cli/output_data.py
  deepomatic/cli/thread_base.py
  deepomatic/cli/workflow/__init__.py
  deepomatic/cli/workflow/cloud_workflow.py
  deepomatic/cli/workflow/json_workflow.py
  deepomatic/cli/workflow/rpc_workflow.py
  requirements.dev.txt
  requirements.txt
  setup.cfg
  setup.py
  tests/test_noop.py
  tests/utils.py
Labels: READY, feature
