Repository Deepomatic/deepocli, pull requests merged in 2020-11, with the labels that each got.

#173 display task id / correlation id on inference error / timeout
  deepomatic/cli/frame.py
  deepomatic/cli/workflow/cloud_workflow.py
  deepomatic/cli/workflow/rpc_workflow.py
  deepomatic/cli/workflow/workflow_abstraction.py
Labels: hacktoberfest-accepted

#169 New Intervention command
  deepomatic/cli/cmds/site/__init__.py
  deepomatic/cli/cmds/site/intervention/__init__.py
  deepomatic/cli/cmds/site/intervention/create.py
  deepomatic/cli/cmds/site/intervention/delete.py
  deepomatic/cli/cmds/site/intervention/inference.py
  deepomatic/cli/cmds/site/intervention/status.py
  deepomatic/cli/cmds/utils.py
  deepomatic/cli/lib/site.py
  dmake.yml
  tests/test_platform.py
  tests/test_site.py
Labels: kind/feature, lifecycle/WIP, priority/medium

#172 Adapt import images requests for views in studio
  deepomatic/cli/cmds/studio.py
  deepomatic/cli/cmds/studio_helpers/file.py
  setup.cfg
  tests/test_studio.py
Labels: kind/stability, lifecycle/READY
